import { Tarefa, TarefasRegistry, EstadoTarefa } from '../../tipos';

const hoje = () => new Date().toISOString();

export const MODELO_TAREFA: Tarefa = {
  id: 'TAREFA-0001',
  titulo: 'Título da tarefa',
  descricao: 'Descrição detalhada.',
  objetivo: 'Objetivo da tarefa.',
  tipo: 'desenvolvimento',
  estado: 'RASCUNHO' as EstadoTarefa,
  prioridade: 'media',
  agenteResponsavel: 'frontend',
  dominio: 'frontend',
  ambiente: 'desenvolvimento',
  dependencias: [],
  contratosObrigatorios: [],
  procedimentosObrigatorios: [],
  arquivosPermitidos: [],
  arquivosProibidos: [],
  contextoNecessario: [],
  criteriosAceitacao: [],
  testesObrigatorios: [],
  riscos: [],
  restricoes: [],
  condicoesDeParada: [],
  criteriosConclusao: [
    'Implementação concluída',
    'Critérios de aceitação atendidos',
    'Testes aprovados',
    'Segurança verificada',
    'Contratos respeitados',
    'Documentação atualizada',
    'Revisão realizada'
  ],
  resultado: {
    resumo: '',
    arquivosAlterados: [],
    testesExecutados: [],
    testesAprovados: [],
    riscosEncontrados: [],
    pendencias: [],
    observacoes: '',
    commit: ''
  },
  aprovacao: { necessaria: false, estado: 'nao_solicitada', aprovador: '', data: null, observacao: '' },
  datas: { criacao: null, criadoEm: null, inicio: null, ultimaAtualizacao: null, atualizadaEm: null, conclusao: null }
};

export function criarTarefasRegistry(): TarefasRegistry {
  return {
    tarefas: [
      {
        id: 'TAR-2026-00001',
        titulo: 'Planejar estrutura do projeto',
        descricao: 'Definir estrutura de pastas, convenções e tarefas para o projeto.',
        objetivo: 'Garantir que o projeto tenha organização básica antes de qualquer implementação.',
        tipo: 'planejamento',
        estado: 'RASCUNHO' as EstadoTarefa,
        prioridade: 'critica',
        agenteResponsavel: 'planejador-arquiteto',
        dominio: 'planejamento',
        ambiente: 'desenvolvimento',
        dependencias: [],
        contratosObrigatorios: [],
        procedimentosObrigatorios: [],
        arquivosPermitidos: [],
        arquivosProibidos: [],
        contextoNecessario: [],
        criteriosAceitacao: ['Estrutura de pastas definida', 'Convenções documentadas', 'Tarefas criadas'],
        testesObrigatorios: [],
        riscos: [],
        restricoes: [],
        condicoesDeParada: [],
        criteriosConclusao: [],
        resultado: {
          resumo: '',
          arquivosAlterados: [],
          testesExecutados: [],
          testesAprovados: [],
          riscosEncontrados: [],
          pendencias: [],
          observacoes: '',
          commit: ''
        },
        aprovacao: { necessaria: false, estado: 'nao_solicitada', aprovador: '', data: null, observacao: '' },
        datas: { criacao: hoje(), criadoEm: hoje(), inicio: null, ultimaAtualizacao: hoje(), atualizadaEm: hoje(), conclusao: null }
      },
      {
        id: 'TAR-2026-00002',
        titulo: 'Criar schema e dados de exemplo',
        descricao: 'Definir estrutura JSON dos produtos e popular com dados de exemplo.',
        objetivo: 'Garantir dados de exemplo para desenvolvimento e testes.',
        tipo: 'banco_de_dados',
        estado: 'RASCUNHO' as EstadoTarefa,
        prioridade: 'media',
        agenteResponsavel: 'banco',
        dominio: 'banco',
        ambiente: 'desenvolvimento',
        dependencias: [],
        contratosObrigatorios: [],
        procedimentosObrigatorios: [],
        arquivosPermitidos: [],
        arquivosProibidos: [],
        contextoNecessario: [],
        criteriosAceitacao: ['Schema JSON definido', 'Dados de exemplo criados', 'Estrutura validada'],
        testesObrigatorios: [],
        riscos: [],
        restricoes: [],
        condicoesDeParada: [],
        criteriosConclusao: [],
        resultado: {
          resumo: '',
          arquivosAlterados: [],
          testesExecutados: [],
          testesAprovados: [],
          riscosEncontrados: [],
          pendencias: [],
          observacoes: '',
          commit: ''
        },
        aprovacao: { necessaria: false, estado: 'nao_solicitada', aprovador: '', data: null, observacao: '' },
        datas: { criacao: hoje(), criadoEm: hoje(), inicio: null, ultimaAtualizacao: hoje(), atualizadaEm: hoje(), conclusao: null }
      },
      {
        id: 'TAR-2026-00003',
        titulo: 'Implementar API CRUD de produtos',
        descricao: 'Criar API REST em memória para gerenciar produtos.',
        objetivo: 'Garantir endpoints funcionais para o frontend.',
        tipo: 'desenvolvimento',
        estado: 'RASCUNHO' as EstadoTarefa,
        prioridade: 'alta',
        agenteResponsavel: 'backend',
        dominio: 'backend',
        ambiente: 'desenvolvimento',
        dependencias: [],
        contratosObrigatorios: [],
        procedimentosObrigatorios: [],
        arquivosPermitidos: [],
        arquivosProibidos: [],
        contextoNecessario: [],
        criteriosAceitacao: ['Endpoints funcionando', 'Validação de dados', 'Códigos HTTP corretos'],
        testesObrigatorios: [],
        riscos: [],
        restricoes: [],
        condicoesDeParada: [],
        criteriosConclusao: [],
        resultado: {
          resumo: '',
          arquivosAlterados: [],
          testesExecutados: [],
          testesAprovados: [],
          riscosEncontrados: [],
          pendencias: [],
          observacoes: '',
          commit: ''
        },
        aprovacao: { necessaria: false, estado: 'nao_solicitada', aprovador: '', data: null, observacao: '' },
        datas: { criacao: hoje(), criadoEm: hoje(), inicio: null, ultimaAtualizacao: hoje(), atualizadaEm: hoje(), conclusao: null }
      },
      {
        id: 'TAR-2026-00004',
        titulo: 'Criar interface web do catálogo',
        descricao: 'Desenvolver página HTML com formulário e tabela para gerenciar produtos.',
        objetivo: 'Garantir interface funcional para usuário.',
        tipo: 'desenvolvimento_frontend',
        estado: 'RASCUNHO' as EstadoTarefa,
        prioridade: 'alta',
        agenteResponsavel: 'frontend',
        dominio: 'frontend',
        ambiente: 'desenvolvimento',
        dependencias: [],
        contratosObrigatorios: [],
        procedimentosObrigatorios: [],
        arquivosPermitidos: [],
        arquivosProibidos: [],
        contextoNecessario: [],
        criteriosAceitacao: ['Página carrega corretamente', 'Formulário funciona', 'Lista atualiza em tempo real'],
        testesObrigatorios: [],
        riscos: [],
        restricoes: [],
        condicoesDeParada: [],
        criteriosConclusao: [],
        resultado: {
          resumo: '',
          arquivosAlterados: [],
          testesExecutados: [],
          testesAprovados: [],
          riscosEncontrados: [],
          pendencias: [],
          observacoes: '',
          commit: ''
        },
        aprovacao: { necessaria: false, estado: 'nao_solicitada', aprovador: '', data: null, observacao: '' },
        datas: { criacao: hoje(), criadoEm: hoje(), inicio: null, ultimaAtualizacao: hoje(), atualizadaEm: hoje(), conclusao: null }
      }
    ],
    estatisticas: {
      total: 4,
      RASCUNHO: 4,
      PLANEJADA: 0,
      PRONTA: 0,
      EM_EXECUCAO: 0,
      TESTES: 0,
      REVISAO: 0,
      APROVACAO: 0,
      BLOQUEADA: 0,
      CONCLUIDA: 0,
      CANCELADA: 0,
      planejador: 1,
      banco: 1,
      backend: 1,
      frontend: 1
    }
  };
}

export const DIRS_TAREFA = ['rascunho', 'planejadas', 'prontas', 'execucao', 'testes', 'revisao', 'aprovacao', 'bloqueadas', 'concluidas'] as const;
